# title of website
title: daohang

# description of website
description: letwearego's navigation site

# favicon of website
favicon: "https://github.com/letwearego.png?size=40"

# your website url
url: https://letwearego.github.io/daohang/

# github profile url
github: "https://github.com/letwearego"

# footer message
footer: © 2021-2021 @letwearego

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
google_analytics: "G-EXE1PJ8CR2"

webstack:
  search:
    enabled: true
    default: google
    # 可选的搜索引擎
    engines:
      - google
      - github
      - weibo
      - baidu
      - bilibili
      - zhihu

content:
  categories:
    - name: 常用推荐
      sites:
        - name: Dribbble
          description: 全球UI设计师作品分享平台。
          url: https://dribbble.com/
        - name: Behance
          description: Adobe旗下的设计师交流平台，来自世界各地的设计师在这里分享自己的作品。
          url: https://behance.net/
        - name: UI中国
          description: 图形交互与界面设计交流、作品展示、学习平台。
          url: http://www.ui.cn/
        - name: 站酷
          description: 中国人气设计师互动平台
          url: http://www.zcool.com.cn/
        - name: Pinterest
          description: 全球美图收藏采集站
          url: https://www.pinterest.com/
        - name: 花瓣
          description: 收集灵感,保存有用的素材
          url: http://huaban.com/
        - name: 优设
          description: 设计师交流学习平台
          url: http://www.uisdc.com/
        - name: Producthunt
          description: 发现新鲜有趣的产品
          url: https://www.producthunt.com/
        - name: Youtube
          description: 全球最大的学习分享平台
          url: https://www.youtube.com/
        - name: Google
          description: 全球最大的UI学习分享平台
          url: https://www.google.com/
        - name: Medium
          description: Read, write and share stories that matter
          url: https://medium.com/
    - name: 界面灵感
      sites:
        - name: 咕噜素材
          description: 质量很高的设计素材网站（推荐）
          url: https://www.gulusucai.com/
        - name: 设计周刊
          description: 最新设计资讯（每天更新）
          url: https://www.shejizhoukan.com/
        - name: 字体仓库
          description: 最全的免费商用字体库
          url: https://www.ziticangku.com/
        - name: 电鸭社区
          description: 国内最早的远程工作社区，也是互联网工作者们的聚集地，非常适合设计开发小伙伴关注
          url: https://eleduck.com/
    - name: 社区资讯
      sites:
        - name: 雷锋网
          description: 人工智能和智能硬件领域的互联网科技媒体
          url: https://www.leiphone.com/
        - name: 36kr
          description: 创业资讯、科技新闻
          url: http://36kr.com/
        - name: 数英网
          description: 数字媒体及职业招聘网站
          url: https://www.digitaling.com/
        - name: 猎云网
          description: 互联网创业项目推荐和创业创新资讯
          url: http://www.lieyunwang.com/
        - name: 人人都是产品经理
          description: 产品经理、产品爱好者学习交流平台
          url: http://www.woshipm.com/
        - name: 互联网早读课
          description: 互联网行业深度阅读与学习平台
          url: https://www.zaodula.com/
        - name: 产品壹佰
          description: 为产品经理爱好者提供最优质的产品资讯、原创内容和相关视频课程
          url: http://www.chanpin100.com/
        - name: PMCAFF
          description: 中国第一产品经理人气组织，专注于研究互联网产品
          url: http://www.pmcaff.com/
        - name: 爱运营
          description: 网站运营人员学习交流，专注于网站产品运营管理、淘宝运营。
          url: http://www.iyunying.org/
        - name: 鸟哥笔记
          description: 移动互联网第一干货平台
          url: http://www.niaogebiji.com/
        - name: 古田路9号
          description: 国内专业品牌创意平台
          url: http://www.gtn9.com/
        - name: 优阁网
          description: UI设计师学习交流社区
          url: http://www.uigreat.com/
    - name: 发现产品
      sites:
        - name: NEXT
          description: 不错过任何一个新产品
          url: http://next.36kr.com/posts
        - name: 少数派
          description: 高品质数字消费指南
          url: https://sspai.com/
        - name: 利器
          description: 创造者和他们的工具
          url: http://liqi.io/
        - name: Today
          description: 为身边的新产品喝彩
          url: http://today.itjuzi.com/
        - name: 小众软件
          description: 在这里发现更多有趣的应用
          url: https://faxian.appinn.com/
        - name: Pttrns
          description: Check out the finest collection of design patterns, resources, mobile apps and inspiration
          url: https://www.pttrns.com/
        - name: Collect UI
          description: Daily inspiration collected from daily ui archive and beyond.
          url: http://collectui.com/
        - name: UI uigreat
          description: APP界面截图参考
          url: http://ui.uigreat.com/
        - name: Android Niceties
          description: A collection of screenshots encompassing some of the most beautiful looking Android apps.
          url: http://androidniceties.tumblr.com/
    - name: 网页灵感
      sites:
        - name: Awwwards
          description: Awwwards are the Website Awards that recognize and promote the talent and effort of the best developers, designers and web agencies in the world.
          url: https://www.awwwards.com/
        - name: CSS Design Awards
          description: Website Awards & Inspiration - CSS Gallery
          url: https://www.cssdesignawards.com/
        - name: The FWA
          description: FWA - showcasing innovation every day since 2000
          url: https://thefwa.com/
        - name: Ecommercefolio
          description: Only the Best Ecommerce Design Inspiration
          url: http://www.ecommercefolio.com/
        - name: Lapa
          description: The best landing page design inspiration from around the web.
          url: http://www.lapa.ninja/
        - name: Reeoo
          description: web design inspiration and website gallery
          url: http://reeoo.com/
        - name: Designmunk
          description: Best Homepage Design Inspiration
          url: https://designmunk.com/
        - name: Best Websites Gallery
          description: Website Showcase Inspiration | Best Websites Gallery
          url: https://bestwebsite.gallery/
        - name: Pages
          description: Curated directory of the best Pages
          url: http://www.pages.xyz/
        - name: SiteSee
          description: SiteSee is a curated gallery of beautiful, modern websites collections.
          url: https://sitesee.co/
        - name: Site Inspire
          description: A CSS gallery and showcase of the best web design inspiration.
          url: https://www.siteinspire.com/
        - name: WebInspiration
          description: 网页设计欣赏,全球顶级网页设计
          url: http://web.uedna.com/
        - name: navnav
          description: A ton of CSS, jQuery, and JavaScript responsive navigation examples, demos, and tutorials from all over the web.
          url: http://navnav.co/
        - name: Really Good UX
          description: A library of screenshots and examples of really good UX. Brought to you by
          url: https://www.reallygoodux.io/    
       
    - name: PPT资源
      sites:
        - name: OfficePLUS
          description: OfficePLUS，微软Office官方在线模板网站！
          url: http://www.officeplus.cn/Template/Home.shtml
        - name: 优品PPT
          description: 高质量的模版，而且还有PPT图表，PPT背景图等资源
          url: http://www.ypppt.com/
        - name: PPT+
          description: PPT加直播、录制和分享—PPT+语音内容分享平台
          url: http://www.pptplus.cn/
        - name: PPTMind
          description: 分享高端ppt模板与keynote模板的数字作品交易平台
          url: http://www.pptmind.com/
        - name: tretars
          description: The best free Mockups from the Web
          url: http://www.tretars.com/ppt-templates
        - name: 5百丁
          description: 中国领先的PPT模板共享平台
          url: http://ppt.500d.me/
   
    - name: 交互动效
      sites:
        - name: Adobe After Effects CC
          description: 电影般的视觉效果和动态图形。
          url: https://www.adobe.com/cn/products/aftereffects/
        - name: principle
          description: Animate Your Ideas, Design Better Apps
          url: http://principleformac.com/
        - name: flinto
          description: Flinto is a Mac app used by top designers around the world to create interactive and animated prototypes of their app designs.
          url: https://www.flinto.com/
        - name: framer
          description: Design everything from detailed icons to high-fidelity interactions—all in one place.
          url: https://framer.com/
        - name: ProtoPie
          description: 高保真交互原型设计
          url: http://www.protopie.cn/
    
        
    -  
     
      sites:
        - name: 
          description:  
          url:  
        - name:  
          description: 
          url: 
        - name:  
          description: 
          url:  
        - name:  
          description:  
          url:  
    
  
    - name: 交互设计
      sites:
        - name: Little Big Details
          description: Little Big Details is a curated collection of the finer details of design, updated every day.
          url: http://littlebigdetails.com/
        - name: Smashing Magazine
          description: Below you’ll find the best tips to take not only your UX design process but also the experiences you craft to the next level.
          url: https://www.smashingmagazine.com/category/user-experience
        - name: nngroup
          description: Evidence-Based User Experience Research, Training, and Consulting
          url: https://www.nngroup.com/articles/
        - name: Boxes and Arrows
          description: Boxes and Arrows is devoted to the practice, innovation, and discussion of design; including graphic design, interaction design, information architecture and the design of business.
          url: http://boxesandarrows.com/
        - name: UX Design Weekly
          description: get a hand picked list of the best user experience design links every week.
          url: http://uxdesignweekly.com/
        - name: UX Ren
          description: 用户体验人的专业社区
          url: http://uxren.cn/
    - name: UED团队
      sites:
        - name: Airbnb Design
          description: Airbnb Design
          url: https://airbnb.design
        - name: Facebook Design
          description: Facebook Design
          url: http://facebook.design/
        - name: Google Design
          description: Google Design
          url: https://design.google/
        - name: eico design
          description: 数字化咨询与产品专家
          url: http://eicodesign.com/
        - name: nice design
          description: nicedesign奈思设计是领先的用户体验设计与互联网品牌建设公司
          url: http://www.niceui.cn/
        - name: 腾讯CDC
          description: 腾讯CDC关注于互联网视觉设计、交互设计、用户研究、前端开发。
          url: http://cdc.tencent.com/
        - name: TGideas
          description: TGideas隶属于腾讯公司互动娱乐业务系统的专业推广类设计团队
          url: http://tgideas.qq.com/
        - name: ISUX
          description: 腾讯社交用户体验设计部
          url: https://isux.tencent.com/
        - name: MXD
          description: 腾讯MIG无线互联网事业群设计团队
          url: http://mxd.tencent.com/
        - name: Aliued
          description: 阿里巴巴国际UED团队
          url: http://www.aliued.com/
        - name: U一点
          description: 阿里巴巴（中国站）用户体验设计部博客U一点设计 UED团队
          url: http://www.aliued.cn/
        - name: 网易uedc
          description: 网易用户体验设计中心（User Experience Design Center）
          url: http://uedc.163.com/
        - name: 百度用户体验中心
          description: 百度用户体验中心
          url: http://ued.baidu.com/
        - name: 京东设计中心
          description: 京东设计中心
          url: http://jdc.jd.com/
        - name: 百度企业产品用户体验中心
          description: 百度企业产品用户体验中心
          url: http://eux.baidu.com/
        - name: 携程设计委员会
          description: 携程设计委员会-Ctrip Design Committee
          url: http://ued.ctrip.com/
